site_name: Foundation Model Benchmarking Tool (FMBench)
repo_name: aws-samples/foundation-model-benchmarking-tool
repo_url: https://github.com/aws-samples/foundation-model-benchmarking-tool
edit_uri: https://github.com/aws-samples/foundation-model-benchmarking-tool/edit/master/
site_url: https://foundation-model-benchmarking-tool.github.io
use_directory_urls: false
 

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

theme:
  name: material
  logo: ./img/fmbt-small.png
  favicon: website/img/favicon.png
  features:
    - navigation
    - content.code.copy
  palette:
      - scheme: default
        primary: light-blue
        accent: light-blue
        toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
      - scheme: slate
        primary: black
        accent: deep-orange
        toggle:
            icon: material/weather-night
            name: Switch to light mode
  edit_uri: ''

extra:
  analytics:
    provider: google
    property: G-MX1DMWF4GF
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aws-samples/foundation-model-benchmarking-tool
    - icon: fontawesome/brands/slack
      link: https://github.com/aws-samples/foundation-model-benchmarking-tool
plugins:
  - search
  - mknotebooks

nav: 
  - Home: 
      - index.md
      - Announcement: announcement.md
  - Getting started:
      - Main: gettingstarted.md
      - CLI: cli.md
      - Features: features.md
      - Workflow: workflow.md
      - SageMaker: quickstart.md      
      - EC2: ec2.md
      - Quarto: quarto.md
  - Benchmarking:
      - Main: benchmarking.md
      - Model evaluations: accuracy.md
      - Bedrock: benchmarking_on_bedrock.md
      - Sagemaker: benchmarking_on_sagemaker.md
      - EKS: benchmarking_on_eks.md
      - EC2: benchmarking_on_ec2.md
      - Neuron: neuron.md
      - Docker: run_as_container.md
  
  - Configs:
      - Files: manifest.md
  - Advanced functionality:
      - Main: advanced.md
      - BYO endpoint: byoe.md
      - BYO REST predictor: byo_rest_predictor.md
      - BYO dataset: byo_dataset.md
      - Build FMBench: build.md
      - Analytics: analytics.md
      - Running multiple model copies: mm_copies.md

  - Results:
      - Report: results.md
      - Website: website.md

  - Releases:
      - Major release: announcement.md
      - releases.md
  - Resources:
      - resources.md
